@port=8000
@identlyCheckValue = 4711

### get short valid JWT
GET http://localhost:{{port}}/token/short
Content-Type: application/json
Idently-Custom-Check: {{identlyCheckValue}}
Secret-Code: v2KHYBicm
Source: dummy-next

### get long valid JWT
GET http://localhost:{{port}}/token/long
Content-Type: application/json
Idently-Custom-Check: {{identlyCheckValue}}
Secret-Code: j8f1yIML6
Source: dummy

### verify JWT
GET http://localhost:{{port}}/token/verify
Authorization: Bearer <<PUT TOKEN HERE>>
Idently-Custom-Check: {{identlyCheckValue}}
Source: dummy-next

### get all users with admin JWT
GET http://localhost:{{port}}/users
Authorization: Bearer <<PUT TOKEN HERE>>
Idently-Custom-Check: {{identlyCheckValue}}
