apiVersion: apps/v1
kind: Deployment
metadata:
  name: idently
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idently
  template:
    metadata:
      labels:
        app: idently
    spec:
      containers:
        - name: idently
          image: idently:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: users-file
              mountPath: /app/config/users.json
              subPath: users.json
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 1
          resources:
            requests:
              cpu: '30m'
              memory: '32Mi'
            limits:
              cpu: '100m'
              memory: '256Mi'
      volumes:
        - name: users-file
          configMap:
            name: idently-config
